### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/comscore/Analytics;

### ISSUE THREAD

**Issue by jnagel33** [segment-integrations/analytics-kotlin-comscore#4]
**Describe the bug**

We are currently attempting to migrate from the classic sdk to the new kotlin sdk. We were able to migrate everything over but we are seeing logs indicating that the comscore plugin is no longer working on the new sdk.

```
[Segment Warning Skipping plugin due to Exception: com.segment.analytics.kotlin.destinations.comscore.ComscoreDestination@fee9a0
[Segment ERROR Caught Exception applying closure to plugin: com.segment.analytics.kotlin.destinations.comscore.ComscoreDestination@fee9a0: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/comscore/Analytics;
```

```
        val analytics = Analytics(BuildConfig.SEGMENT_WRITE_KEY, applicationContext)
        analytics.add(plugin = ComscoreDestination())
```        

**To Reproduce**
1. install comscore destination library version 1.5.0
2. Add comscore plugin - `analytics.add(plugin = ComscoreDestination())`
3. send an analytics track event
4. See error posted above

**Expected behavior**
No error, plugin works without errors

**Platform (please complete the following information):**
 - Library Version in use: 1.5.0
 - Platform being tested: Android
 - Integrations in use: Firebase and Comscore

**Comment by alanjcharles** [comment]
Hi @jnagel33 ! In order to streamline the reporting and escalation process internally, we are disabling Github Issues for this repository. If you are still experiencing this issue please send a copy of your report, as well as any other information you might have, to `friends@segment.com`  so we can prioritize it accordingly. Thanks and apologies for the inconvenience!
